git:
  depth: 3
  quiet: true

branches:
  only:
    - syncing

before_install:
  - export TZ='Asia/Shanghai'
  - git remote add upstream https://github.com/Kong/homebrew-kong.git
  - git fetch upstream
  - git checkout upstream/master
  - rename 's/openresty/kong-openresty/' Formula/*.rb
  - sed -i 's/^\s*\([Cc]lass\)\s\+[Oo]penresty\s\+\(<\s\+Formula\)\s*/\1 KongOpenresty \2/g' Formula/kong-openresty.rb
  # - sed -i '/bin\.install_symlink/d' Formula/kong-openresty.rb
  - sed -i 's/\(['"'"'"'']\)kong\/kong\/openresty\(\@[0-9\.]\+['"'"'"'']\)\s*/\1issenn\/kong\/kong-openresty\2/g' Formula/kong.rb
  - sed -i 's/^\s*\([Cc]lass\)\s\+[Oo]penresty\(AT[0-9]\+\s\+<\s\+Formula\)\s*/\1 KongOpenresty\2/g' Formula/kong-openresty@*.rb
  # - sed -i '/bin\.install_symlink/d' Formula/kong-openresty@1.13.6.2.rb
  - sed -i 's/\(Library\/Taps\/\)kong/\1issenn/g' .travis.yml
  - sed -i 's/kong\(\/kong\)/issenn\1/g' README.md
  - >
      KONG_VERSION="$(grep -E '\s+version\s('"'|"'")' Formula/kong-openresty.rb | awk '{print $2}' | tr -d '"'"|'"'')"
      && rm Aliases/openresty@"${KONG_VERSION}"
      && cd Aliases
      && ln -s ../Formula/kong-openresty.rb kong-openresty@"${KONG_VERSION}"
      && cd -

script:
  - git rm Formula/openresty.rb Formula/openresty@1.13.6.2.rb Aliases/openresty@1.15.8.2
  - git add -A
  - git commit -m "Change openresty to kong-openresty."
  # - git push -f origin HEAD:master

deploy:
  provider: pages
  skip_cleanup: true
  repo: issenn/homebrew-kong
  target_branch: master
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  keep_history: true
  verbose: false
  on:
    branch: syncing
